import { existsSync, mkdirSync, readdirSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { dirname, join, relative, resolve, sep } from "node:path";
import { resolveConfig } from "./config-validation.js";
import type { DualmarkSvelteKitConfig, ResolvedDualmarkSvelteKitConfig } from "./types.js";
import type { Plugin } from "vite";

const GENERATED_MARKER = "// @generated by @dualmark/sveltekit; do not edit";

export type DualmarkSvelteKitPlugin = Plugin;

export interface GeneratedRouteSpec {
  routePath: string;
  filePath: string;
  source: string;
}

function normalizePath(pathname: string): string {
  const withSlash = pathname.startsWith("/") ? pathname : `/${pathname}`;
  return withSlash.replace(/\/+$/, "") || "/";
}

function routePathToServerFile(routesDir: string, routePath: string): string {
  const parts = normalizePath(routePath).split("/").filter(Boolean);
  return join(routesDir, ...parts, "+server.ts");
}

function toPosixPath(pathname: string): string {
  return pathname.split(sep).join("/");
}

function stripImportExtension(specifier: string): string {
  return specifier.replace(/\.(c|m)?(t|j)sx?$/, "");
}

function importSpecifier(fromFile: string, targetFile: string): string {
  const fromDir = dirname(fromFile);
  let specifier = toPosixPath(relative(fromDir, targetFile));
  if (!specifier.startsWith(".")) specifier = `./${specifier}`;
  return stripImportExtension(specifier);
}

function collectionDetailSource(configImport: string, collectionName: string): string {
  return `${GENERATED_MARKER}
import { createDualmarkRouteHandler } from "@dualmark/sveltekit";
import dualmarkConfig from ${JSON.stringify(configImport)};

const handler = createDualmarkRouteHandler(dualmarkConfig, {
  kind: "collection-detail",
  collectionName: ${JSON.stringify(collectionName)},
});

export const prerender = true;
export const GET = handler.GET;
export const entries = handler.entries;
`;
}

function markdownRouteSource(configImport: string): string {
  return `${GENERATED_MARKER}
import { createDualmarkRouteHandler } from "@dualmark/sveltekit";
import dualmarkConfig from ${JSON.stringify(configImport)};

const handler = createDualmarkRouteHandler(dualmarkConfig);

export const prerender = true;
export const GET = handler.GET;
`;
}

function parameterizedRouteSource(configImport: string, pattern: string): string {
  return `${GENERATED_MARKER}
import { createDualmarkRouteHandler } from "@dualmark/sveltekit";
import dualmarkConfig from ${JSON.stringify(configImport)};

const handler = createDualmarkRouteHandler(dualmarkConfig, {
  kind: "parameterized",
  pattern: ${JSON.stringify(pattern)},
});

export const prerender = true;
export const GET = handler.GET;
export const entries = handler.entries;
`;
}

function llmsTxtSource(configImport: string): string {
  return `${GENERATED_MARKER}
import { createLlmsTxtHandler } from "@dualmark/sveltekit";
import dualmarkConfig from ${JSON.stringify(configImport)};

const handler = createLlmsTxtHandler(dualmarkConfig);

export const prerender = true;
export const GET = handler.GET;
`;
}

function staticMarkdownPath(pattern: string): string {
  if (pattern === "/") return "/index.md";
  return `${normalizePath(pattern)}.md`;
}

export function createRouteSpecs(
  input: DualmarkSvelteKitConfig,
  projectRoot: string,
): GeneratedRouteSpec[] {
  const resolved: ResolvedDualmarkSvelteKitConfig = resolveConfig(input);
  const routesDir = resolve(projectRoot, resolved.routesDir);
  const configPath = resolve(projectRoot, resolved.configPath);
  const specs: GeneratedRouteSpec[] = [];

  function add(routePath: string, makeSource: (configImport: string) => string): void {
    const filePath = routePathToServerFile(routesDir, routePath);
    const configImport = importSpecifier(filePath, configPath);
    specs.push({
      routePath,
      filePath,
      source: makeSource(configImport),
    });
  }

  for (const [collectionName, collectionConfig] of Object.entries(resolved.collections)) {
    const route = collectionConfig.route ?? collectionName;
    const slugSegment = collectionConfig.slugStrategy === "single" ? "[slug]" : "[...slug]";
    add(`/${route}/${slugSegment}.md`, (configImport) =>
      collectionDetailSource(configImport, collectionName),
    );
    if (collectionConfig.emitListing !== false) {
      add(`/${route}.md`, markdownRouteSource);
    }
  }

  for (const staticPage of resolved.staticPages) {
    add(staticMarkdownPath(staticPage.pattern), markdownRouteSource);
  }

  for (const parameterizedRoute of resolved.parameterizedRoutes) {
    add(`${normalizePath(parameterizedRoute.pattern)}.md`, (configImport) =>
      parameterizedRouteSource(configImport, parameterizedRoute.pattern),
    );
  }

  if (resolved.llmsTxt?.enabled) {
    add("/llms.txt", llmsTxtSource);
  }

  return specs;
}

function writeGeneratedFile(filePath: string, source: string): void {
  if (existsSync(filePath)) {
    const current = readFileSync(filePath, "utf8");
    if (!current.startsWith(GENERATED_MARKER)) {
      throw new Error(
        `[@dualmark/sveltekit] Refusing to overwrite user-authored route file: ${filePath}`,
      );
    }
  }
  mkdirSync(dirname(filePath), { recursive: true });
  writeFileSync(filePath, source, "utf8");
}

function collectGeneratedRouteFiles(dir: string): string[] {
  if (!existsSync(dir)) return [];
  const generated: string[] = [];
  for (const entry of readdirSync(dir, { withFileTypes: true })) {
    const entryPath = join(dir, entry.name);
    if (entry.isDirectory()) {
      generated.push(...collectGeneratedRouteFiles(entryPath));
      continue;
    }
    if (entry.name !== "+server.ts" && entry.name !== "+server.js") continue;
    const current = readFileSync(entryPath, "utf8");
    if (current.startsWith(GENERATED_MARKER)) {
      generated.push(entryPath);
    }
  }
  return generated;
}

function removeStaleGeneratedFiles(routesDir: string, activeFiles: ReadonlySet<string>): void {
  for (const filePath of collectGeneratedRouteFiles(routesDir)) {
    if (!activeFiles.has(filePath)) {
      rmSync(filePath);
    }
  }
}

export function generateDualmarkRoutes(
  input: DualmarkSvelteKitConfig,
  projectRoot: string,
): GeneratedRouteSpec[] {
  const specs = createRouteSpecs(input, projectRoot);
  const activeFiles = new Set(specs.map((spec) => spec.filePath));
  const resolved = resolveConfig(input);
  removeStaleGeneratedFiles(resolve(projectRoot, resolved.routesDir), activeFiles);
  for (const spec of specs) {
    writeGeneratedFile(spec.filePath, spec.source);
  }
  return specs;
}

export function dualmarkSvelteKit(input: DualmarkSvelteKitConfig): DualmarkSvelteKitPlugin {
  let projectRoot = process.cwd();

  return {
    name: "@dualmark/sveltekit",
    enforce: "pre",
    configResolved(config) {
      projectRoot = config.root;
    },
    buildStart() {
      generateDualmarkRoutes(input, projectRoot);
    },
  };
}
