import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join, relative, resolve, sep } from "node:path";
import { resolveConfig } from "./config-validation.js";
import type { DualmarkRemixConfig } from "./types.js";

export interface GeneratedRouteSpec {
  readonly routePath: string;
  readonly fileName: string;
  readonly source: string;
}

export interface ReactRouterRouteConfigEntry {
  readonly path: string;
  readonly file: string;
}

const GENERATED_MARKER = "// @generated by @dualmark/remix; do not edit";

function normalizePath(pathname: string): string {
  const withSlash = pathname.startsWith("/") ? pathname : `/${pathname}`;
  return withSlash.replace(/\/+$/g, "") || "/";
}

function staticMarkdownPath(pattern: string): string {
  if (pattern === "/") return "index.md";
  return `${normalizePath(pattern).slice(1)}.md`;
}

export function toReactRouterPath(pattern: string): string {
  return normalizePath(pattern)
    .slice(1)
    .replace(/\[([^\]]+)\]/g, (_, key: string) => `:${key}`);
}

function safeFileName(routePath: string): string {
  return `${routePath.replace(/[:/*[\]\\.]+/g, "-").replace(/^-+|-+$/g, "")}.ts`;
}

function resourceSource(configImport: string, target?: string): string {
  const targetArg = target ? `, ${target}` : "";
  return `${GENERATED_MARKER}
import { createDualmarkResourceRoute } from "@dualmark/remix";
import dualmarkConfig from ${JSON.stringify(configImport)};

const route = createDualmarkResourceRoute(dualmarkConfig${targetArg});

export const loader = route.loader;
export const action = route.action;
`;
}

function llmsTxtSource(configImport: string): string {
  return `${GENERATED_MARKER}
import { createLlmsTxtResourceRoute } from "@dualmark/remix";
import dualmarkConfig from ${JSON.stringify(configImport)};

const route = createLlmsTxtResourceRoute(dualmarkConfig);

export const loader = route.loader;
export const action = route.action;
`;
}

export function createRouteSpecs(
  input: DualmarkRemixConfig,
  configImport = "../app/dualmark.config",
): readonly GeneratedRouteSpec[] {
  const resolved = resolveConfig(input);
  const specs: GeneratedRouteSpec[] = [];
  for (const [collectionName, collectionConfig] of Object.entries(resolved.collections)) {
    const route = collectionConfig.route ?? collectionName;
    const detailPath = `${route}/:slug.md`;
    specs.push({
      routePath: detailPath,
      fileName: safeFileName(detailPath),
      source: resourceSource(
        configImport,
        `{ kind: "collection-detail", collectionName: ${JSON.stringify(collectionName)} }`,
      ),
    });
    if (collectionConfig.emitListing !== false) {
      const listingPath = `${route}.md`;
      specs.push({
        routePath: listingPath,
        fileName: safeFileName(listingPath),
        source: resourceSource(configImport),
      });
    }
  }
  for (const staticPage of resolved.staticPages) {
    const routePath = staticMarkdownPath(staticPage.pattern);
    specs.push({ routePath, fileName: safeFileName(routePath), source: resourceSource(configImport) });
  }
  for (const parameterizedRoute of resolved.parameterizedRoutes) {
    const routePath = toReactRouterPath(`${parameterizedRoute.pattern}.md`);
    specs.push({
      routePath,
      fileName: safeFileName(routePath),
      source: resourceSource(
        configImport,
        `{ kind: "parameterized", pattern: ${JSON.stringify(parameterizedRoute.pattern)} }`,
      ),
    });
  }
  if (resolved.llmsTxt?.enabled) {
    specs.push({
      routePath: "llms.txt",
      fileName: "llms-txt.ts",
      source: llmsTxtSource(configImport),
    });
  }
  return specs;
}

export function dualmarkRoutes(input: DualmarkRemixConfig): readonly ReactRouterRouteConfigEntry[] {
  const resolved = resolveConfig(input);
  const routeFileBase = resolved.generatedDir.replace(/^app\//, "");
  generateRouteFiles(input, process.cwd());
  return createRouteSpecs(input).map((spec) => ({
    path: spec.routePath,
    file: `${routeFileBase}/${spec.fileName}`,
  }));
}

function toPosixPath(pathname: string): string {
  return pathname.split(sep).join("/");
}

function stripImportExtension(specifier: string): string {
  return specifier.replace(/\.(c|m)?(t|j)sx?$/, "");
}

function importSpecifier(fromFile: string, targetFile: string): string {
  const fromDir = dirname(fromFile);
  let specifier = toPosixPath(relative(fromDir, targetFile));
  if (!specifier.startsWith(".")) specifier = `./${specifier}`;
  return stripImportExtension(specifier);
}

function writeGeneratedFile(filePath: string, source: string): void {
  if (existsSync(filePath)) {
    const current = readFileSync(filePath, "utf8");
    if (!current.startsWith(GENERATED_MARKER)) {
      throw new Error(`[@dualmark/remix] Refusing to overwrite user-authored route file: ${filePath}`);
    }
  }
  mkdirSync(dirname(filePath), { recursive: true });
  writeFileSync(filePath, source, "utf8");
}

export function generateRouteFiles(
  input: DualmarkRemixConfig,
  projectRoot: string,
): readonly GeneratedRouteSpec[] {
  const resolved = resolveConfig(input);
  const generatedDir = resolve(projectRoot, resolved.generatedDir);
  const configPath = resolve(projectRoot, resolved.configPath);
  const configImport = importSpecifier(join(generatedDir, "__generated__.ts"), configPath);
  const specs = createRouteSpecs(input, configImport);
  for (const spec of specs) writeGeneratedFile(join(generatedDir, spec.fileName), spec.source);
  return specs;
}

export { GENERATED_MARKER };
