import { existsSync, mkdirSync, mkdtempSync, readFileSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { describe, expect, it } from "vitest";
import { createRouteSpecs, generateDualmarkRoutes } from "../src/plugin.js";
import type { DualmarkSvelteKitConfig } from "../src/types.js";

const config: DualmarkSvelteKitConfig = {
  siteUrl: "https://example.com",
  collections: {
    posts: {
      converter: "blog",
      slugStrategy: "single",
      getEntries: () => [],
    },
  },
  staticPages: [{ pattern: "/", render: () => "# Home" }],
  parameterizedRoutes: [
    {
      pattern: "/topics/[topic]",
      getStaticPaths: () => [{ params: { topic: "aeo" } }],
      render: ({ params }) => `# ${params.topic}`,
    },
  ],
  llmsTxt: { enabled: true, brandName: "Example", sections: [] },
};

describe("createRouteSpecs", () => {
  it("maps config to SvelteKit +server.ts route files", () => {
    const root = mkdtempSync(join(tmpdir(), "dualmark-sveltekit-"));
    const specs = createRouteSpecs(config, root);
    const routePaths = specs.map((spec) => spec.routePath);

    expect(routePaths).toContain("/posts/[slug].md");
    expect(routePaths).toContain("/posts.md");
    expect(routePaths).toContain("/index.md");
    expect(routePaths).toContain("/topics/[topic].md");
    expect(routePaths).toContain("/llms.txt");
    expect(specs.map((spec) => spec.filePath)).toContain(
      join(root, "src/routes/posts/[slug].md/+server.ts"),
    );
  });
});

describe("generateDualmarkRoutes", () => {
  it("writes generated route files", () => {
    const root = mkdtempSync(join(tmpdir(), "dualmark-sveltekit-"));
    const specs = generateDualmarkRoutes(config, root);
    const detail = join(root, "src/routes/posts/[slug].md/+server.ts");

    expect(existsSync(detail)).toBe(true);
    expect(readFileSync(detail, "utf8")).toContain("@generated by @dualmark/sveltekit");
    expect(specs).toHaveLength(5);
  });

  it("refuses to overwrite user-authored route files", () => {
    const root = mkdtempSync(join(tmpdir(), "dualmark-sveltekit-"));
    const detail = join(root, "src/routes/posts/[slug].md/+server.ts");
    mkdirSync(join(root, "src/routes/posts/[slug].md"), { recursive: true });
    writeFileSync(detail, "export const GET = () => new Response('mine');\n", {
      encoding: "utf8",
      flag: "wx",
    });

    expect(() => generateDualmarkRoutes(config, root)).toThrow(/Refusing to overwrite/);
  });

  it("removes stale generated route files when config changes", () => {
    const root = mkdtempSync(join(tmpdir(), "dualmark-sveltekit-"));
    const detail = join(root, "src/routes/posts/[slug].md/+server.ts");

    generateDualmarkRoutes(config, root);
    expect(existsSync(detail)).toBe(true);

    generateDualmarkRoutes({ ...config, collections: {} }, root);
    expect(existsSync(detail)).toBe(false);
  });
});
