name = "dualmark-fastly-example"
description = "Example Fastly Compute project using Dualmark"
language = "javascript"
manifest_version = 3

[scripts]
  build = "npm run build"

[setup]
  [setup.backends]
    [setup.backends.origin_backend]
      address = "example.com"
      port = 443

[local_server]
  [local_server.backends]
    [local_server.backends.origin_backend]
      url = "http://127.0.0.1:4000"

