name = "dualmark-fastly-compute"
description = "Dualmark Fastly Compute example"
language = "javascript"
manifest_version = 3
main = "src/index.ts"

[setup]

  [setup.backends]

    [setup.backends.origin_0]
      address = "example.com"
