import { existsSync, mkdirSync, mkdtempSync, readFileSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { describe, expect, it } from "vitest";
import { generateDualmarkRoutes } from "../src/plugin.js";

describe("generateDualmarkRoutes", () => {
  it("writes generated route files", () => {
    const root = mkdtempSync(join(tmpdir(), "dualmark-remix-"));
    const specs = generateDualmarkRoutes(
      {
        siteUrl: "https://example.com",
        collections: {
          posts: { converter: "blog", slugStrategy: "single", getEntries: () => [] },
        },
      },
      root,
    );

    expect(specs.length).toBe(2);
    const detail = join(root, "app/.dualmark-remix/posts-slug-md.ts");
    expect(existsSync(detail)).toBe(true);
    expect(readFileSync(detail, "utf8")).toContain('from "../dualmark.config"');
  });

  it("refuses to overwrite user-authored files", () => {
    const root = mkdtempSync(join(tmpdir(), "dualmark-remix-"));
    const generatedDir = join(root, "app/.dualmark-remix");
    mkdirSync(generatedDir, { recursive: true });
    writeFileSync(join(generatedDir, "posts-slug-md.ts"), "export const mine = true;\n");

    expect(() =>
      generateDualmarkRoutes(
        {
          siteUrl: "https://example.com",
          collections: {
            posts: { converter: "blog", slugStrategy: "single", getEntries: () => [] },
          },
        },
        root,
      ),
    ).toThrow(/Refusing to overwrite/);
  });

  it("removes stale generated route files", () => {
    const root = mkdtempSync(join(tmpdir(), "dualmark-remix-"));
    const stale = join(root, "app/.dualmark-remix/posts-slug-md.ts");

    generateDualmarkRoutes(
      {
        siteUrl: "https://example.com",
        collections: {
          posts: { converter: "blog", slugStrategy: "single", getEntries: () => [] },
        },
      },
      root,
    );
    expect(readFileSync(stale, "utf8")).toContain("@generated by @dualmark/remix");

    generateDualmarkRoutes({ siteUrl: "https://example.com", collections: {} }, root);

    expect(existsSync(stale)).toBe(false);
  });
});
